-- noinspection SqlNoDataSourceInspectionForFile

INSERT INTO USER (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE, PHONE, FULL_NAME)
VALUES (0, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN', '+36305556699', 'ADMIN BÉLA');

INSERT INTO USER (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE, PHONE, FULL_NAME)
VALUES (1, 0, 'user', 'user@gmail.com', 'user', 'USER', '', '');

INSERT INTO ADS (ID, VERSION, ADVERTISER_ID, ADTYPE, STATUS, TITLE, DESCRIPTION, PICTURE_PATH)
VALUES (0, 0, 0, 'FORSALE', 'WAITING', 'FEHÉR CICA ELADÓ', 'SALALALALALALAAL', '');

INSERT INTO ADS (ID, VERSION, ADVERTISER_ID, ADTYPE, STATUS, TITLE, DESCRIPTION, PICTURE_PATH)
VALUES (1, 0, 0, 'WOULDBUY', 'APPROVED', 'CICA ELADÓ', 'szeretnék ilyen cicáát', '');

INSERT INTO ADS (ID, VERSION, ADVERTISER_ID, ADTYPE, STATUS, TITLE, DESCRIPTION, PICTURE_PATH)
VALUES (2, 0, 0, 'FORSALE', 'APPROVED', 'SZÉP CICA JÓ CICA', 'SALALALALALALAL', 'https://material.angular.io/assets/img/examples/shiba2.jpg');

INSERT INTO ADS (ID, VERSION, ADVERTISER_ID, ADTYPE, STATUS, TITLE, DESCRIPTION, PICTURE_PATH)
VALUES (3, 0, 0, 'LOST', 'APPROVED', 'SZÉP CICA MÁSIK CICA', 'SALALALALALALAASDASDASDL', 'https://i.imgur.com/zHB9qdQ.jpg');