-- noinspection SqlNoDataSourceInspectionForFile

INSERT INTO USER (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE)
VALUES (0, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');

INSERT INTO USER (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE)
VALUES (1, 0, 'user', 'user@gmail.com', 'user', 'USER');

INSERT INTO ADS (ID, VERSION, ADVERTISER_ID, ADTYPE, STATUS, TITLE)
VALUES (0, 0, 0, 'FORSALE', 'WAITING', 'FEHÉR CICA ELADÓ');

INSERT INTO ADS (ID, VERSION, ADVERTISER_ID, ADTYPE, STATUS, TITLE)
VALUES (1, 0, 0, 'FORSALE', 'WAITING', 'CICA ELADÓ');

INSERT INTO ADS (ID, VERSION, ADVERTISER_ID, ADTYPE, STATUS, TITLE, DESCRIPTION, PICTURE_PATH)
VALUES (2, 0, 0, 'FORSALE', 'APPROVED', 'SZÉP CICA JÓ CICA', 'SALALALALALALAL', 'https://material.angular.io/assets/img/examples/shiba2.jpg');

INSERT INTO ADS (ID, VERSION, ADVERTISER_ID, ADTYPE, STATUS, TITLE, DESCRIPTION, PICTURE_PATH)
VALUES (3, 0, 0, 'FORSALE', 'APPROVED', 'SZÉP CICA MÁSIK CICA', 'SALALALALALALAASDASDASDL', 'https://i.imgur.com/zHB9qdQ.jpg');